backend:
  name: github
  repo: eldridger/mrmiagi

media_folder: static/assets
public_folder: assets
collections:
  - name: pages
    label: "Pages"
    files:
      - file: "src/content/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - { label: "Template Key", name: "template-key", widget: "hidden", default: "landing-page" }
          - { label: "Title", name: "title", widget: string }
          - { label: "Heading", name: "heading", widget: string }
          - { label: Intro text, name: intro, widget: text }


  - name: site
    label: "Site Options"
    files:
      - label: "Header"
        name: header
        file: "_data/header.yml"
        fields:
          - { name: "header-title", label: "Header Title", widget: "string" }
      - label: "Footer"
        name: footer
        file: "_data/footer.yml"
        fields:
          - { name: "footer-title", label: "Footer Title", widget: "string" }


  - name: blog
    label: Blog
    folder: blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }